# Configuration for Intelligent IDE

# Application Settings
app:
  name: Intelligent IDE
  version: 1.0.0
  description: AI-powered developer productivity tool
  environment: development # Options: development, staging, production

# Server Configuration
server:
  host: 0.0.0.0
  frontend_port: 3000
  backend_port: 5000
  ci_port: 5001
  debug: true # Enable debug mode in development

# Database Configuration
database:
  type: postgres
  host: db
  port: 5432
  name: ide_db
  user: postgres
  password: ${DB_PASSWORD} # Loaded from .env file

# OpenAI API Configuration
openai:
  api_key: ${OPENAI_API_KEY} # Loaded from .env file
  default_model: gpt-4
  max_tokens: 2000
  temperature: 0.7

# Docker Configuration
docker:
  registry: ${DOCKER_REGISTRY} # Loaded from .env file
  image_prefix: intelligent-ide
  networks:
    - name: ide-network
      driver: bridge

# Code Execution Settings
code_execution:
  timeout: 10 # Seconds
  max_memory: 512 # MB
  supported_languages:
    - javascript
    - python
    - java
    - csharp
    - cpp
  execution_environments:
    javascript:
      image: node:16-alpine
      command: node
    python:
      image: python:3.9-slim
      command: python
    java:
      image: openjdk:11-slim
      command: java
    csharp:
      image: mcr.microsoft.com/dotnet/sdk:6.0
      command: dotnet run
    cpp:
      image: gcc:latest
      command: g++

# Test Generation Settings
testing:
  frameworks:
    javascript: jest
    python: pytest
    java: junit
    csharp: xunit
    cpp: googletest

# CI/CD Pipeline Settings
ci_pipeline:
  stages:
    - static_analysis
    - unit_testing
    - build
    - deployment
  environments:
    - development
    - staging
    - production
  automatic_deployment: true
  deploy_only_on_success: true

# Security Settings
security:
  sanitize_code: true
  rate_limiting: true
  max_requests_per_minute: 60
  authentication_required: true

# Logging Configuration
logging:
  level: info # Options: debug, info, warning, error
  format: json
  output: file
  file_path: /var/log/intelligent-ide.log

# Feature Flags
features:
  ai_code_generation: true
  ai_test_generation: true
  ai_debugging: true
  continuous_integration: true
  code_review: true